Add Flex Dapps proposal implementation
tracer-protocol/proposals pull request #11
Opened 2021-08-25 03:26 UTC by sporejack

# 10 - Flex Dapps
#10

2021-08-25 04:17 UTC, ScaredIbis requested changes
Contract calls all look correct,  just had some minor feedback on the documentation. Verified the following:

 - [x] USDC call uses 6 decimals
 - [x] USDC address is correct
 - [x] TCR call uses 18 decimals
 - [x] TCR address is correct
 - [x] TCR vesting contract address is correct
 - [x] Flex Dapps Ethereum address matches [their ENS registration](https://app.ens.domains/name/flexdapps.eth)
 - [x] Timestamp is correct as per [snapshot](https://vote.tracer.finance/#/tracer.eth/proposal/QmdTqbvQ3gBDbMoaWNP6WmESGurFdkU4fcnRoNrQadNcAc)

2021-08-25 04:17 UTC, ScaredIbis commented on proposals/10-flex-dapps-proposal.md
> +Data: [`0xa9059cbb000000000000000000000000dd140cb2847f6186a9df3b25ae1e135052b0932100000000000000000000000000000000000000000000000000000006fc23ac00`,`0x0d535883000000000000000000000000dd140cb2847f6186
Would have thought this should match the final output

2021-08-25 04:33 UTC, ScaredIbis commented on proposals/10-flex-dapps-proposal.md
> +                    "value": "1621476000"
on second thought this timestamp corresponds to Thursday, 20 May 2021 12:00:00 GMT+10 but not sure what timezone the [snapshot](https://vote.tracer.finance/#/tracer.eth/proposal/QmdTqbvQ3gBDbMoaWNP6WmESGurFdkU4fcnRoNrQadNcAc) would be displaying times in, wouldn't be suprised if that was UTC

2021-08-25 05:15 UTC, raymogg commented on proposals/10-flex-dapps-proposal.md
> +    0x0d535883000000000000000000000000dd140cb2847f6186a9df3b25ae1e135052b0932100000000000000000000000000000000000000000001a784379d99db420000000000000000000000000000009c4a4204b79dd291d6b6571c5be8bbcd0
Looks like the payload here has `isFixed` equal to `true` (note the 1 between the token address and cliff weeks

2021-09-27 13:21 UTC, antoniopgs commented on proposals/10-flex-dapps-proposal.md
> +                    "value": "1621476000"
@ScaredIbis I already looked into that. Snapshot converts dates to your local timezone.
Explanation here: https://github.com/tracer-protocol/proposals/issues/16

Leaving this here for anyone else who needs to calculate block.timestamps of snapshot dates:
```javascript
/*
    Snapshot converts dates to your system's current timezone, but Date constructor converts from system back to UTC
    Therefore, you can pass in params for the snapshot date you see on your computer
*/
const snapshotDateToEVMTimestamp = (year, month, day, hours, minutes) => {
    const monthIndex = month - 1; // Date constructor uses monthIndex, not month
    const snapshotDate = new Date(year, monthIndex, day, hours, minutes);
    console.log(snapshotDate); // will show in utc
    const evmTimestamp = Math.floor(snapshotDate.getTime() / 1000); // convert to unix epoch
    console.log(evmTimestamp); // will show in unix epoch (same unit as evm block.timestamp)
}
```

2021-09-27 13:22 UTC, antoniopgs approved these changes
Looks good to me.

2021-09-28 02:59 UTC, raymogg commented on proposals/10-flex-dapps-proposal.md
> +Targets: [`0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48`,`0x707b6be09028e78d2a667db7596b2803c112f9b2`]
@sporejack there is a missing target here - looking below though the implementation looks fine. Just pointing out for clarity and a double check

2021-09-28 03:18 UTC, raymogg commented on proposals/10-flex-dapps-proposal.md
> +Data: [`0xa9059cbb000000000000000000000000dd140cb2847f6186a9df3b25ae1e135052b0932100000000000000000000000000000000000000000000000000000006fc23ac00`, `0xa9059cbb000000000000000000000000707b6be09028e78
The second payload here differs to that produced by the DAOCheck tool, but matches the manually produced code. The difference is the amount. I think the DAOCheck tool has the right amount. Can you confirm this?

2021-09-28 05:40 UTC, ScaredIbis commented on proposals/10-flex-dapps-proposal.md
> +Data: [`0xa9059cbb000000000000000000000000dd140cb2847f6186a9df3b25ae1e135052b0932100000000000000000000000000000000000000000000000000000006fc23ac00`, `0xa9059cbb000000000000000000000000707b6be09028e78
had the same concern, only thing stopping me from approving @sporejack

2021-09-29 03:51 UTC, raymogg approved these changes

2021-09-29 03:52 UTC, merged