Add strategic treasury proposal
tracer-protocol/proposals pull request #13
Opened 2021-08-30 09:58 UTC by raymogg

PR for issue #3/

Data has been verified using daocheck tool as well as a manual implementation.

2021-09-01 01:42 UTC, BenjaminPatch approved these changes
This matches with my manually written code to generate

2021-09-01 05:43 UTC, Paul4912 commented on proposals/11-strategic-treasury-diversification.md
> +accounts: `["0x0d298f3220eAdf02D10C9Feff537B50787725418", "0xf8ccf1f5381956f4152B5570627C49D42eABB60e", "0x8938892193FddAB15F113459E91e1c4Ab1f052A4", "0x2ce5f9f52C1eec9a1183f91139C59b485Ff39dAd", "0x
0x7a025ecded9ca07d5C887776391Bf8D4D34Ee11E
I cannot find this address on the doc.
https://www.notion.so/tracerdao/Proposal-11-Strategic-Treasury-Diversification-a1557ad8ec9544a6a1c1b9a597f1bafe

GSR's address on the doc is
0x2f529d5E02A531141516F2B62C1EF48AF8048913

2021-09-01 05:45 UTC, Paul4912 requested changes
halting this until comment is cleared up just to be safe.

2021-09-01 05:50 UTC, Paul4912 commented on proposals/11-strategic-treasury-diversification.md
> +accounts: `["0x0d298f3220eAdf02D10C9Feff537B50787725418", "0xf8ccf1f5381956f4152B5570627C49D42eABB60e", "0x8938892193FddAB15F113459E91e1c4Ab1f052A4", "0x2ce5f9f52C1eec9a1183f91139C59b485Ff39dAd", "0x
Seems like in the json its using the right one so should be fine.

2021-09-06 04:06 UTC, raymogg commented on proposals/11-strategic-treasury-diversification.md
> +accounts: `["0x0d298f3220eAdf02D10C9Feff537B50787725418", "0xf8ccf1f5381956f4152B5570627C49D42eABB60e", "0x8938892193FddAB15F113459E91e1c4Ab1f052A4", "0x2ce5f9f52C1eec9a1183f91139C59b485Ff39dAd", "0x
@Paul4912 good pickup - GSR changed their address on discourse but this did not get propagated across properly.

I'll update this and then re generate the payload

2021-09-06 04:23 UTC, BenjaminPatch approved these changes

2021-09-06 04:40 UTC, Paul4912 approved these changes

2021-09-06 04:40 UTC, Paul4912 commented on proposals/11-strategic-treasury-diversification.md
> +accounts: `["0x0d298f3220eAdf02D10C9Feff537B50787725418", "0xf8ccf1f5381956f4152B5570627C49D42eABB60e", "0x8938892193FddAB15F113459E91e1c4Ab1f052A4", "0x2ce5f9f52C1eec9a1183f91139C59b485Ff39dAd", "0x
looked over it again seems all good as long as 
0x7a025ecded9ca07d5C887776391Bf8D4D34Ee11E
is the correct address for gsr.

2021-09-07 01:11 UTC, merged