Proposal 18
tracer-protocol/proposals pull request #17
Opened 2021-09-23 14:34 UTC by antoniopgs

# Proposal 18 - Chuck Li - Market Making & Advisory
https://github.com/tracer-protocol/proposals/issues/16

2021-09-23 21:59 UTC, mynameuhh commented on proposals/18-chuck-li-market-making-advisory.md
> +Had a quick chat with @mynameuhh, and he advised me to set the `startTime` parameter in the `vest()` function as the time when the Snapshot Proposal passed.
@raymogg  can I ask you to confirm if this is good? Given that it's the classic situation of people putting "when the proposal is executed" without knowing that there might be a delay between snapshot & on-chain

2021-09-23 22:01 UTC, mynameuhh commented on proposals/18-chuck-li-market-making-advisory.md
> +Is "End time" in UTC? Or was it adapted to my timezone?
I believe it is

2021-09-23 22:04 UTC, mynameuhh commented on proposals/18-chuck-li-market-making-advisory.md
> +}
You can also use web3's builtin [toWei function](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#towei)

2021-09-23 22:13 UTC, mynameuhh requested changes

2021-09-23 22:13 UTC, mynameuhh commented on proposals/18-chuck-li-market-making-advisory.md
> +Data: [0x0d5358830000000000000000000000007c1b4b31fd641e1ea73e895b3656d93a659f0d0d000000000000000000000000000000000000000000027b46536c66c8e30000000000000000000000000000009c4a4204b79dd291d6b6571c5be8bb
This is on the right track, but not quite.

There will actually be two steps in this proposal: Transfer into the vesting contract, then call `vest`.

You current `Targets` array contains the TCR token address, which is the correct target for transferring, but your `Data` array contains the data to call `vest` on the vesting contract.

So if you want to transfer first, you will need to generate the proposal data for `TCR.transfer(vestingContract, amount)`, then the proposal data for `vestingContract.vest(vestingSchedule)`.

For reference, you can look at @sporejack's proposal here: https://github.com/tracer-protocol/proposals/blob/ed1d61c0a0091b4117f277c3c41c7dff9eb9e60e/proposals/14-yamashita-proposal. This is slightly different though, because there are two separate vesting schedules, but the idea is the same.

2021-09-24 02:05 UTC, raymogg commented on proposals/18-chuck-li-market-making-advisory.md
> +Had a quick chat with @mynameuhh, and he advised me to set the `startTime` parameter in the `vest()` function as the time when the Snapshot Proposal passed.
Yeah I think we all agree now we take the snapshot pass time as the "proposal executed" time. That way dev implementation delay does not affect vesting.

2021-09-24 05:55 UTC, antoniopgs commented on proposals/18-chuck-li-market-making-advisory.md
> +}
@mynameuhh I know about `toWei`.
The reason I didn't use it is because it adds 18 decimals (because ETH has 18 decimals).

This `toDecimalsExpanded` function I wrote works for tokens with any amount of decimals.

I know that if we're working with tokens with less than 18 decimals, overflows are less likely.
But still, I just wanted to create something technically correct, but also generally applicable.

I might never need it in the future. But if I do, I know it's here.

2021-09-24 05:59 UTC, antoniopgs commented on proposals/18-chuck-li-market-making-advisory.md
> +}
Oh wait!

Actually, I can just pass in one of these parameters (https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#id76) to `toWei` and that will make it work for any amount of decimals... (facepalm)

Haha oh well, now I know.

2021-09-24 06:59 UTC, antoniopgs commented on proposals/18-chuck-li-market-making-advisory.md
> +Data: [0x0d5358830000000000000000000000007c1b4b31fd641e1ea73e895b3656d93a659f0d0d000000000000000000000000000000000000000000027b46536c66c8e30000000000000000000000000000009c4a4204b79dd291d6b6571c5be8bb
That GitHub link doesn't work for me (got a 404).

But yes, you're right. Fixing now...

2021-09-26 22:59 UTC, mynameuhh commented on proposals/18-chuck-li-market-making-advisory.md
> +}
Still good practice! :rocket:

2021-09-27 03:48 UTC, mynameuhh approved these changes
I generated myself and all matches up :+1:

2021-09-27 09:17 UTC, antoniopgs commented on proposals/18-chuck-li-market-making-advisory.md
> +}
Actually, @mynameuhh even if you use `toWei()`, you still have to pick the right denomination of ether (finney, szabo, etc) depending on the amount of decimals of the token.

So this `toDecimalsExpanded` function does come in handy, because it removes that complexity.

Another solution would be something like:

```
const dynamicToWei = (amount, decimals) => {
    switch(decimals) {
        case "18":
            return web3.utils.toWei(amount)

        case "12":
            return web3.utils.toWei(amount, "szabo")

        // and so on..
    }
}
```

2021-12-06 04:55 UTC, raymogg commented
Going through growth fund.

2021-12-06 04:55 UTC, closed without merging