Add Yamashita proposal implementation
tracer-protocol/proposals pull request #8
Opened 2021-08-20 03:24 UTC by sporejack

# Issue
#7 

# Implementation
[DAOCheck](https://github.com/tracer-protocol/DAOCheck) was provided with the proposal plan specified in the proposal implementation text added to the repository by this PR. 

Manual verification was then performed.

2021-08-24 01:20 UTC, sporejack commented
@BenjaminPatch discovered an issue with the initial payload data in that the second call to `vest` (i.e., the **last** call of the entire proposal plan) had `isFixed` set to `true`, when it should have been `false`. This is due to a bug in DAOCheck which we're investigating currently.

I've applied a manual fix in fdee1e0 (please read the commit message there).

2021-08-24 03:04 UTC, BenjaminPatch requested changes

2021-08-24 03:04 UTC, BenjaminPatch commented on proposals/14-yamashita-proposal.md
> +    0x0d53588300000000000000000000000087c2f090997b0e158c10399605d19c41ec47b49b0000000000000000000000000000000000000000000422ca8b0a00a4250000000000000000000000000000009c4a4204b79dd291d6b6571c5be8bbcd0
I might be missing something, but I believe this is still not correct. It corresponds to the proposal data of a vesting contract which has `isFixed` set to `true`, but `isFixed` is `false` for call one (according to the data given starting on line 42)

2021-08-24 04:19 UTC, sporejack commented on proposals/14-yamashita-proposal.md
> +    0x0d53588300000000000000000000000087c2f090997b0e158c10399605d19c41ec47b49b0000000000000000000000000000000000000000000422ca8b0a00a4250000000000000000000000000000009c4a4204b79dd291d6b6571c5be8bbcd0
Missed this in fdee1e0; consult 387916a.

2021-08-25 01:40 UTC, Paul4912 commented
Im reading the proposal and it says "starting on the day that this proposal is executed." Isn't the timestamp you put in the date in the past now?

2021-08-25 01:56 UTC, raymogg approved these changes
Confirmed
- targets are correct
- amounts are correct
- vesting params are correct
- start date (unix timestamp) is correct
- duration is correct
- function signatures are correct
- function call data is correct

Note:
In the order of function calls passed into the generation code, `isFixed` is set to false in call 2 and true in call 3, however in the payload data these are reversed.

2021-08-25 02:00 UTC, raymogg commented
> e

Yeah moving forward we will get proposers to clear up this wording. We are considering proposals passed as when the snapshot vote has passed. This means time between approval and on chain execution does not affect vesting schedules.

2021-08-25 02:34 UTC, raymogg commented
> Im reading the proposal and it says "starting on the day that this proposal is executed." Isn't the timestamp you put in the date in the past now?

Yeah moving forward we will get proposers to clear up this wording. We are considering proposals passed as when the snapshot vote has passed. This means time between approval and on chain execution does not affect vesting schedules.

2021-08-25 03:40 UTC, sporejack commented
> Im reading the proposal and it says "starting on the day that this proposal is executed." Isn't the timestamp you put in the date in the past now?

Yes, because the [vote passed in the past](https://vote.tracer.finance/#/tracer.eth/proposal/QmXJXyfgcJoDXEuHxuZoGT5AqVTpwyBma73kCdfr72t6pf).

2021-09-27 04:15 UTC, sporejack commented
> Note:
> In the order of function calls passed into the generation code, `isFixed` is set to false in call 2 and true in call 3, however in the payload data these are reversed.

Consult 55844c3.

2021-09-27 04:39 UTC, raymogg approved these changes

2021-09-27 05:40 UTC, mynameuhh approved these changes

2021-09-27 05:59 UTC, ScaredIbis approved these changes

2021-09-27 06:21 UTC, merged